version: "3.8"

services:
  go:
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - "postgres"
    networks:
      - fullstack

  postgres:
    image: postgres:alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: v6vpxdkd
      POSTGRES_DB: turingdb
    ports:
      - "5432:5432"
    networks:
      - fullstack
    volumes:
      - database_postgres:/var/lib/postgresql/data

volumes:
  database_postgres:

networks:
  fullstack:
    driver: bridge
